spring.application.name=autoloc-api
server.port=8081

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehcuile
spring.datasource.username=postgres
spring.datasource.password=bechir
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.tn.esprit.autoloc=INFO
logging.level.com.example.projetSI=INFO
